language: common-lisp
sudo: required
services:
- docker
env:
  global:
  - DOCKERHUB_ENDPOINT=elitltd
  - DOCKER_REPO=pgloader
  - secure: "lPWvuaZIY52bgtq3K6eLGA9uPv7Inr5eGi2O/fbsOwqrwA9btnmEyMmvNxhWnnxwpR6rTgmpylmZ2suYhPr6QVRC2+ElhaQadkYuPRJA8+kRULywATJE+V4BUUhUSLqaI88C7IxY8+3zm2GKnpUfI2oIv5zuqkj2Cy4CWi6jIG7Gwi4ZAt/TS4v3fZDWYKihcbpwoxiTzp21DgcUXjwkxEF0dFjvg2o6dIdcUshnddIZJacNsEqkH00/6y42jhPAtQlki4MbKPScSDKeXnULQ/Cex20dYxBt8ILqnTO7X8h7eTbWfq3vV9ZYshmwn2Y08qTojU9DCBDXmmMuxlBxPBl5FqMKRiUCEQUBhbKGLsQZolQPAe5j21VD6PyPwqI9KQsByICOI6DZFEeUY2vyMvdEdezlapkHkoqMmr8p0sCJ4ICVRJr0dccb//qv+aj1uCRxj94SCkY8sPcOcN18Y4c+5g0O8zbXo2Wps7iYwuLiK5sM2RMdkmY+dClhQrGMgBp8BD9tEJ6LK/80by+1lIBDWPAd2kx1pm2++UyIoa4u8kS/UvHf3QfxaULercdQhI8LHgiMpdFSpsjFJwniNPTpOPH2LcPiwbXZSf2db4Z2+O54rw7qsawbAxKsjTwrSvdJzvOwqqJswiftiVQjVM7fPf57zFLLXXX0qVAL40k="
script:
- "./build-docker.sh"
notifications:
  email: false
